# Generated by Django 2.2 on 2020-04-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseTime',
        ),
    ]
